<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Estudio de Entrenamiento de Avatares y Lenguaje Natural</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f0f0f0;
            margin: 0;
            padding: 20px;
        }
        .container {
            max-width: 800px;
            margin: 40px auto;
            background-color: #fff;
            padding: 20px;
            border: 1px solid #ddd;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        h1, h2 {
            color: #333;
        }
        .button {
            background-color: #4CAF50;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s;
        }
        .button:hover {
            background-color: #3e8e41;
        }
        .recuadro {
            background-color: #f9f9f9;
            border: 1px solid #ddd;
            padding: 15px;
            margin: 20px 0;
            border-radius: 8px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
        }
        textarea {
            width: 100%;
            height: 100px;
            margin-top: 10px;
            padding: 10px;
            border-radius: 5px;
            border: 1px solid #ddd;
            resize: none;
        }
        select {
            width: 100%;
            padding: 10px;
            margin-top: 10px;
            border-radius: 5px;
            border: 1px solid #ddd;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Estudio de Entrenamiento de Avatares y Lenguaje Natural</h1>
        <p>Este estudio te permite entrenar avatares y generar entrenamientos de lenguaje natural en una misma interfaz.</p>

        <div class="recuadro">
            <h2>Entrenamiento de Avatares</h2>
            <p>Selecciona un modelo de avatar para entrenar:</p>
            <select id="avatar-model">
                <option value="modelo1">Modelo 1</option>
                <option value="modelo2">Modelo 2</option>
                <option value="modelo3">Modelo 3</option>
            </select>
            <button class="button" id="entrenar-avatar">Entrenar Avatar</button>
        </div>

        <div class="recuadro">
            <h2>Entrenamiento de Lenguaje Natural</h2>
            <p>Selecciona un modelo de lenguaje natural para entrenar:</p>
            <select id="lenguaje-model">
                <option value="modelo1">Modelo 1</option>
                <option value="modelo2">Modelo 2</option>
                <option value="modelo3">Modelo 3</option>
            </select>
            <button class="button" id="entrenar-lenguaje">Entrenar Lenguaje</button>
        </div>

        <div class="recuadro">
            <h2>Texto a Voz</h2>
            <p>Ingresa un texto para convertir a voz:</p>
            <textarea id="texto-a-voz" placeholder="Escribe el texto aquí..."></textarea>
            <button class="button" id="convertir-a-voz">Convertir a Voz</button>
        </div>

        <div class="recuadro">
            <h2>Movimientos de Avatar</h2>
            <p>Selecciona un movimiento para el avatar:</p>
            <select id="movimiento-avatar">
                <option value="movimiento1">Movimiento 1</option>
                <option value="movimiento2">Movimiento 2</option>
                <option value="movimiento3">Movimiento 3</option>
            </select>
            <button class="button" id="aplicar-movimiento">Aplicar Movimiento</button>
        </div>
    </div>

    <script>
        // Código JavaScript para interactuar con los elementos de la interfaz

        document.getElementById('entrenar-avatar').addEventListener('click', function() {
            const avatarModel = document.getElementById('avatar-model').value;
            alert(Entrenando el ${avatarModel});
        });

        document.getElementById('entrenar-lenguaje').addEventListener('click', function() {
            const lenguajeModel = document.getElementById('lenguaje-model').value;
            alert(Entrenando el modelo de lenguaje ${lenguajeModel});
        });

        document.getElementById('convertir-a-voz').addEventListener('click', function() {
            const texto = document.getElementById('texto-a-voz').value;
            alert(Convertiendo el siguiente texto a voz: "${texto}");
        });

        document.getElementById('aplicar-movimiento').addEventListener('click', function() {
            const movimiento = document.getElementById('movimiento-avatar').value;
            alert(Aplicando el movimiento: ${movimiento});
        });
    </script>
</body>
</html>
